### ISSUE TITLE
Powershell commands error messages not available

### ISSUE THREAD

**Issue by WilliamRaphaWyde** [wynsure/script.cli#11]
https://github.com/wynsure/script.cli/blob/9b5df63eb8f425651021532003fc4aacbc136f88/src/db.ts#L75

Actually, it's critical that Powershell errors are somehow available for diagnosis purpose.

For example:

- current version above, no powershell error messages available in 
- version disaplying error messages in standard with error ( cf. https://github.com/wynsure/script.cli/pull/10 )

<img width="1065" alt="image" src="https://github.com/wynsure/script.cli/assets/55548823/42c2fce6-411f-4e3b-9208-66629d1c38ec">

_NB: From my quick test, it seems 1> nul does not allow error messages (only) to be printed to standard output for some reason._

**Comment by JeromeCugny** [comment]
I added that to not leak info in production.  
After talking with the team, you're right that we should allow some display for debugging purpose. But it should depend on an option to still be silent in production mode:
- env var like `ODBC_CREATION_MODE` (production or debug) and/or additional param to `createODBC`
- default to production mode
- add the `2>nul` only on production

Note:  
`-ErrorAction SilentlyContinue` at https://github.com/wynsure/script.cli/blob/9b5df63eb8f425651021532003fc4aacbc136f88/src/db.ts#L81 doesn't work because it's misplaced:
- it's a parameter for `powershell.exe`, not for the command run
- it's not an error to fail to remove the connection if it doesn't exist

For the redirection:
- `2>nul` only redirects the stderr to "nul", so it only hides the errors not regular messages
- our commands don't show anything on success, so it's not a big deal
- `1>nul` redirects the standard output (stdout) to "nul" => hide the regular messages
- so technically we should add both in production mode

**Comment by WilliamRaphaWyde** [comment]
About the parameter:

Regarding env var, for simplicity purpose I would prefer not to introduce a new variable. If it makes sense, can we we reuse NODE_ENV, an existing environment variable (already leveraged by WynsureEnvRoot)?

A new createODBC option (with default = production) is OK with me also, since it would delegate the responsibility to the calling script.

**Comment by JeromeCugny** [comment]
> About the parameter:
> 
> Regarding env var, for simplicity purpose I would prefer not to introduce a new variable. If it makes sense, can we we reuse NODE_ENV, an existing environment variable (already leveraged by WynsureEnvRoot)?
> 
> A new createODBC option (with default = production) is OK with me also, since it would delegate the responsibility to the calling script.

Then we should go for the additional param `createODBC(options: ODBCParams, mode: "production" | "development" = "production")` and let the caller use an env var if needed.  
We're also using that script on other clients without wynsureenvroot
